//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrderingBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid AddressId { get; set; }
        public int AddressTypeId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
